/**
 * THE ENERGY NETWORK — the terrain's luminous surface.
 *
 * (Client, 2026-08-03 round 3: "instead of a plain dark surface, build an
 * illuminated digital landscape made from thousands of glowing green
 * particles connected by extremely thin energy lines... every contour of the
 * terrain should be visible because luminous particle streams naturally
 * follow the elevation of the ground.")
 *
 * Nothing here is painted onto the land — every element is generated by
 * SAMPLING THE REAL HEIGHTFIELD, which is the entire trick. A line bends over
 * a hill because it literally walked over the hill; brightness accumulates on
 * a ridge because the line's vertices measured their own prominence when they
 * got there. The network cannot disagree with the terrain, at any scale,
 * because it has no independent opinion.
 *
 * Four layers, one group:
 *
 *   lines    polylines advected across the surface through a blend of the
 *            CONTOUR direction (wrapping landforms like elevation isolines)
 *            and the DOWNSLOPE direction (draining into basins like water),
 *            plus rotational noise wander. Two families — contour-followers
 *            and flow-lines — so the whole reads as one drainage system,
 *            never as concentric rings. GL lines are 1px thin by nature:
 *            "extremely thin energy lines" is the platform default here.
 *   scatter  thousands of dim surface particles — the ground's grain
 *   hubs     bright nodes at genuine local summits, found by scanning the
 *            field — the only place the palette reaches yellow-green
 *   motes    microscopic particles floating just above the surface, drifting
 *            slowly — the air between the viewer and the land
 *
 * Density is NEVER uniform: seeds are accepted against crest × cluster
 * probability (the same cluster field the mesh glow bakes), so live regions
 * carry dense constellations and quiet regions stay almost empty — and the
 * two always agree, because they are one field.
 *
 * All of it is deterministic (seeded RNG, fixed camera acceptance test) and
 * static after construction: motion is entirely in the shaders (gentle
 * travelling pulses, slow twinkle, mote drift), all wall-clock, all far too
 * slow to read as animation. The world is alive, not busy.
 */

import * as THREE from "three";
import { CAMERA, TERRAIN, WORLD, type Tier } from "@/lib/config";
import { centreline } from "../centreline";
import { glowClusterAt, valueNoise2, type TerrainHandle } from "./terrain";

export interface TerrainNetworkHandle {
  group: THREE.Group;
  update(elapsed: number): void;
  setPointScale(scale: number): void;
  dispose(): void;
}

/** Deterministic PRNG. Math.random() anywhere in the scene makes every
 *  visual check flake — which looks like flaky tests rather than a bug. */
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const f = (v: number) => v.toFixed(4);

// ---------------------------------------------------------------------------
// Shaders
// ---------------------------------------------------------------------------

/** Shared colour ramp: near-black green → deep emerald/forest → toxic →
 *  electric lime. Injected as uniforms so lines and points stay one palette. */
const RAMP_GLSL = /* glsl */ `
uniform vec3 uC0;
uniform vec3 uC1;
uniform vec3 uC2;
uniform vec3 uC3;

vec3 ramp(float t){
  vec3 c = mix(uC0, uC1, smoothstep(0.0, 0.4, t));
  c = mix(c, uC2, smoothstep(0.4, 0.75, t));
  c = mix(c, uC3, smoothstep(0.75, 1.0, t));
  return c;
}
`;

function lineVert(): string {
  const [n0, n1] = TERRAIN.network.nearFade;
  return /* glsl */ `
attribute float aBright;
attribute float aPath;
attribute float aRnd;

varying float vBright;
varying float vFog;
varying float vPath;
varying float vRnd;

void main(){
  vec4 world = modelMatrix * vec4(position, 1.0);
  float viewDist = distance(cameraPosition, world.xyz);

  // The same two laws every luminous element obeys: the ground at the
  // viewer's feet stays calm (near fade), and distance dims ADDITIVE light
  // toward zero rather than mixing it toward the fog colour.
  vBright = aBright * smoothstep(${f(n0)}, ${f(n1)}, viewDist);
  // DEPTH GRADE (world-polish pass): a plane-separation term on top of the
  // fog. The near and mid network reads in full; the far network recedes to
  // embers, so foreground, midground and distance stop competing and the
  // world layers itself.
  vBright *= mix(1.0, 0.4, smoothstep(950.0, 1900.0, viewDist));
  float fog = clamp((viewDist - ${f(WORLD.fogNear)}) /
                    ${f(WORLD.fogFar - WORLD.fogNear)}, 0.0, 1.0);
  vFog = pow(fog, 1.2);
  vPath = aPath;
  vRnd = aRnd;

  gl_Position = projectionMatrix * viewMatrix * world;
}
`;
}

function lineFrag(): string {
  const P = TERRAIN.network.pulse;
  return /* glsl */ `
precision highp float;

uniform float uTime;
uniform float uMaster;
${RAMP_GLSL}

varying float vBright;
varying float vFog;
varying float vPath;
varying float vRnd;

void main(){
  float b = vBright;

  // Occasional luminous streams travelling the line, following the ground's
  // own contours because the line does. GENTLE: ~46u/s. Gated per line so
  // under half the network streams at any moment; the rest holds still.
  float gate = step(fract(vRnd * 13.73), ${f(P.fraction)});
  float ph = fract(vPath * ${f(1 / P.wavelength)} - uTime * ${f(P.speed / P.wavelength)} + vRnd * 7.0);
  float band = pow(max(0.0, sin(ph * 6.28318) * 0.5 + 0.5), 6.0);
  b *= 1.0 + ${f(P.gain)} * band * gate;

  // Slow per-line breathing, phase-scattered. Never a collective pulse.
  b *= 0.92 + 0.08 * sin(uTime * (0.3 + vRnd * 0.5) + vRnd * 6.28318);

  vec3 col = ramp(clamp(b, 0.0, 1.0));
  gl_FragColor = vec4(col * b * uMaster * (1.0 - vFog * 0.93), 1.0);
}
`;
}

function pointVert(maxPx: number, drift: boolean): string {
  const [n0, n1] = TERRAIN.network.nearFade;
  return /* glsl */ `
attribute float aSize;
attribute float aBright;
attribute float aRnd;

uniform float uTime;
uniform float uPointScale;

varying float vBright;
varying float vFog;

void main(){
  vec3 p = position;
${
  drift
    ? /* glsl */ `
  // Mote drift: slow closed orbits a few units wide. An absolute function of
  // time, never integrated, so a four-hour tab never wanders anywhere.
  float w = 0.05 + aRnd * 0.06;
  float a1 = 2.0 + aRnd * 3.0;
  p.x += sin(uTime * w * 6.28318 + aRnd * 43.0) * a1;
  p.z += cos(uTime * w * 4.9 + aRnd * 91.0) * a1;
  p.y += sin(uTime * w * 3.1 + aRnd * 17.0) * (1.0 + aRnd * 2.2);
`
    : ""
}
  vec4 world = modelMatrix * vec4(p, 1.0);
  float viewDist = distance(cameraPosition, world.xyz);

  float tw = 0.82 + 0.18 * sin(uTime * (0.5 + aRnd * 1.7) + aRnd * 6.28318);
  vBright = aBright * smoothstep(${f(n0)}, ${f(n1)}, viewDist) * tw;
  // Same depth grade as the lines — one law, every layer.
  vBright *= mix(1.0, 0.4, smoothstep(950.0, 1900.0, viewDist));
  float fog = clamp((viewDist - ${f(WORLD.fogNear)}) /
                    ${f(WORLD.fogFar - WORLD.fogNear)}, 0.0, 1.0);
  vFog = pow(fog, 1.2);

  gl_Position = projectionMatrix * viewMatrix * world;

  float att = clamp(${f(TERRAIN.network.sizeAttenuation)} / max(viewDist, 1.0), 0.05, 2.0);
  float size = aSize * uPointScale * att * (0.75 + 0.5 * clamp(vBright, 0.0, 1.0));
  gl_PointSize = min(size, ${f(maxPx)});
}
`;
}

const POINT_FRAG = /* glsl */ `
precision highp float;

uniform float uMaster;
uniform vec3 uCore;
${RAMP_GLSL}

varying float vBright;
varying float vFog;

void main(){
  vec2 uv = gl_PointCoord - 0.5;
  float d = length(uv) * 2.0;
  if (d > 1.0) discard;
  float disc = pow(1.0 - d, 1.7);

  vec3 col = ramp(clamp(vBright, 0.0, 1.0));
  // Only the strongest concentrations push toward yellow-green — hub cores.
  col = mix(col, uCore, smoothstep(0.78, 1.0, vBright));
  gl_FragColor = vec4(col * (vBright * disc) * uMaster * (1.0 - vFog * 0.93), 1.0);
}
`;

// ---------------------------------------------------------------------------

export function createTerrainNetwork(
  terrain: TerrainHandle,
  tier: Tier,
): TerrainNetworkHandle {
  const N = TERRAIN.network;
  const G = TERRAIN.glow;
  const rng = mulberry32(TERRAIN.noiseSeed ^ 0x9e3779b9);
  const range = (lo: number, hi: number) => lo + (hi - lo) * rng();

  /**
   * The acceptance camera — same construction as the particle seeds'. The
   * network covers what the viewer can see (with margin for parallax and
   * aspect) and spends nothing outside it.
   */
  const seedCam = new THREE.PerspectiveCamera(CAMERA.fov, 16 / 9, CAMERA.near, CAMERA.far);
  seedCam.position.set(...CAMERA.basePosition);
  seedCam.lookAt(new THREE.Vector3(...CAMERA.baseTarget));
  seedCam.updateMatrixWorld(true);
  seedCam.updateProjectionMatrix();
  const camWorld = new THREE.Vector3(...CAMERA.basePosition);
  const probe = new THREE.Vector3();

  const visible = (x: number, z: number, margin: number): boolean => {
    probe.set(x, terrain.heightAt(x, z) + 3, z);
    probe.project(seedCam);
    return (
      Math.abs(probe.x) <= margin &&
      probe.y >= -1.4 &&
      probe.y <= 1.45 &&
      probe.z <= 1
    );
  };

  const B = WORLD.bounds;

  /**
   * THE GATHER (world-polish pass, 2026-08-03): "the energy flowing through
   * the terrain should naturally become the energy flowing through the
   * bridge — no visible transition." Network brightness rises smoothly as
   * the ground approaches the bridge's own line, so the land's light
   * visibly converges on the structure's roots and the road: the bridge is
   * the highest expression of an energy that was already everywhere.
   *
   * Plan-distance to the centreline, from 64 baked samples — the exact
   * curve, cheaply, at bake time only.
   */
  const clSamples = new Float32Array(64 * 2);
  {
    const v = new THREE.Vector3();
    for (let i = 0; i < 64; i++) {
      centreline.positionAt(i / 63, v);
      clSamples[i * 2] = v.x;
      clSamples[i * 2 + 1] = v.z;
    }
  }
  const gatherAt = (x: number, z: number): number => {
    let d2 = Infinity;
    for (let i = 0; i < 64; i++) {
      const dx = x - clSamples[i * 2];
      const dz = z - clSamples[i * 2 + 1];
      const q = dx * dx + dz * dz;
      if (q < d2) d2 = q;
    }
    return 1 - THREE.MathUtils.smoothstep(Math.sqrt(d2), 60, 340);
  };

  const crestAt = (x: number, z: number) =>
    THREE.MathUtils.clamp(terrain.prominenceAt(x, z) / G.crestNorm, 0, 1);
  /** NEGATIVE prominence is a drainage channel — the floor of a valley cut
   *  below its surroundings. The brief's "major flowing terrain paths" are
   *  exactly these, and they carry energy like the ridges do: the luminous
   *  rivers in the reference run THROUGH the valleys, not over the peaks. */
  const channelAt = (x: number, z: number) =>
    THREE.MathUtils.clamp(-terrain.prominenceAt(x, z) / G.crestNorm, 0, 1);
  const elevAt = (h: number) => THREE.MathUtils.smoothstep(h, G.elevLow, G.elevHigh);

  // --- LINES ---------------------------------------------------------------

  const lPos: number[] = [];
  const lBright: number[] = [];
  const lPath: number[] = [];
  const lRnd: number[] = [];

  /** Interleaved (x,y,z,size,bright,rnd) records, unpacked into the scatter
   *  buffers below — the nodes that sit ON the lines. */
  const lineNodes: number[] = [];

  const nrm = new THREE.Vector3();
  const linesTarget = N.linesByTier[tier];
  let lines = 0;
  let guard = linesTarget * 60;

  while (lines < linesTarget && guard-- > 0) {
    const sx = range(B.minX + 30, B.maxX - 30);
    const sz = range(B.minZ + 30, B.maxZ - 30);
    if (!visible(sx, sz, 1.35)) continue;
    probe.set(sx, terrain.heightAt(sx, sz), sz);
    if (probe.distanceTo(camWorld) < 340) continue;

    // Density: (crest × cluster) × SLOPE. The slope term is load-bearing
    // (second probe round): on near-flat ground the contour direction is
    // undefined, so a line seeded there is pure wander — the frame filled
    // with faint spaghetti that traced nothing. Lines live on relief, where
    // "following the elevation" is a visible, meaningful act; the plains
    // keep only a sparse remainder.
    const slopeW = THREE.MathUtils.smoothstep(terrain.slopeAt(sx, sz), 3, 14);
    const relief = Math.max(crestAt(sx, sz), channelAt(sx, sz) * 0.9);
    const p =
      (0.15 + 0.85 * (0.55 * glowClusterAt(sx, sz) + 0.45 * relief)) *
      (0.22 + 0.78 * Math.max(slopeW, channelAt(sx, sz)));
    if (rng() > Math.pow(p, 1.35)) continue;

    const isFlow = rng() < N.flowFraction;
    const bias = isFlow
      ? range(N.flowBias[0], N.flowBias[1])
      : range(N.contourBias[0], N.contourBias[1]);
    const side = rng() < 0.5 ? -1 : 1;
    const trunk = rng() < N.trunkFraction;
    const energy = (0.35 + 0.65 * rng()) * (trunk ? 1.4 : 1);
    const steps = Math.round(range(N.segments[0], N.segments[1]));
    const lineRnd = rng();
    const wSeed = Math.floor(rng() * 0xffffff);

    const pts: number[] = [];
    const bright: number[] = [];
    let dirX = 0;
    let dirZ = 0;
    let havePrev = false;
    let px = sx;
    let pz = sz;
    /** Accumulated signed heading change. A contour line orbiting a small
     *  knoll closes into a RING — the artificial-wireframe look the brief
     *  bans, and the second probe round showed a field of them. No line may
     *  turn through more than ~1.2 revolutions. */
    let turned = 0;

    for (let s = 0; s <= steps; s++) {
      terrain.normalAt(px, pz, nrm);
      // For a heightfield the normal's xz components point DOWNHILL — the
      // march's two ingredients both come straight from the real surface.
      let gx = nrm.x;
      let gz = nrm.z;
      const gl = Math.hypot(gx, gz);
      let cx: number;
      let cz: number;
      if (gl < 1e-4) {
        const a = rng() * Math.PI * 2;
        cx = Math.cos(a);
        cz = Math.sin(a);
        gx = cx;
        gz = cz;
      } else {
        gx /= gl;
        gz /= gl;
        cx = -gz * side;
        cz = gx * side;
      }

      let dx = cx * (1 - bias) + gx * bias;
      let dz = cz * (1 - bias) + gz * bias;
      // Rotational wander so no line is ever geometric.
      const ang =
        valueNoise2(px * 0.004 + lineRnd * 90, pz * 0.004 - lineRnd * 70, wSeed) *
        N.wander;
      const ca = Math.cos(ang);
      const sa = Math.sin(ang);
      const rx = dx * ca - dz * sa;
      const rz = dx * sa + dz * ca;
      if (havePrev) {
        dx = THREE.MathUtils.lerp(rx, dirX, N.turnSmooth);
        dz = THREE.MathUtils.lerp(rz, dirZ, N.turnSmooth);
      } else {
        dx = rx;
        dz = rz;
      }
      const dl = Math.hypot(dx, dz) || 1;
      const nx = dx / dl;
      const nz = dz / dl;
      if (havePrev) {
        turned += Math.atan2(dirX * nz - dirZ * nx, dirX * nx + dirZ * nz);
        if (Math.abs(turned) > 7.5) break;
      }
      dirX = nx;
      dirZ = nz;
      havePrev = true;

      px += dirX * N.step;
      pz += dirZ * N.step;
      if (px < B.minX + 10 || px > B.maxX - 10 || pz < B.minZ + 10 || pz > B.maxZ - 10)
        break;

      const h = terrain.heightAt(px, pz);
      pts.push(px, h + N.lift, pz);
      // Brightness measured AT each vertex: ridges bright, valleys dark,
      // quiet regions quiet — the line dims and brightens as it travels the
      // relief, which is what makes the topography legible from light alone.
      // The base term carries the line through ordinary ground (first probe
      // round: at 0.2 the network was arithmetically invisible — a 1px
      // additive line needs ~0.3 luminance before a dark frame registers it).
      // The slope factor dims the stretches where a line crosses flat ground
      // — the plain goes quiet under it, the climb re-ignites it. Channels
      // are exempt: a drainage floor is flat AND luminous, because that is
      // where the flow-lines collect into the valleys' bright rivers.
      const vSlope = THREE.MathUtils.smoothstep(terrain.slopeAt(px, pz), 2, 12);
      const vChan = channelAt(px, pz);
      bright.push(
        energy *
          (0.42 + 0.45 * Math.max(crestAt(px, pz), vChan) + 0.28 * elevAt(h)) *
          (0.3 + 0.7 * glowClusterAt(px, pz)) *
          (0.35 + 0.65 * Math.max(vSlope, vChan)) *
          (1 + 0.55 * gatherAt(px, pz)),
      );
    }

    const m = pts.length / 3;
    if (m < 8) continue;

    const fade = Math.max(2, Math.floor(m * 0.08));
    for (let k = 0; k < m - 1; k++) {
      for (const kk of [k, k + 1]) {
        const taper = Math.min(1, Math.min(kk, m - 1 - kk) / fade);
        lPos.push(pts[kk * 3], pts[kk * 3 + 1], pts[kk * 3 + 2]);
        lBright.push(bright[kk] * taper * taper);
        lPath.push(kk * N.step);
        lRnd.push(lineRnd);
      }
    }

    // NODES ON THE LINES — "glowing particles CONNECTED BY thin energy
    // lines" needs the particles to sit on the lines, not merely near them.
    // Every ~6-10th vertex that carries real energy becomes a node.
    const nodeEvery = 6 + Math.floor(lineRnd * 5);
    for (let k = nodeEvery; k < m - 2; k += nodeEvery) {
      if (bright[k] < 0.18) continue;
      lineNodes.push(
        pts[k * 3], pts[k * 3 + 1] + 0.4, pts[k * 3 + 2],
        1.6 + rng() * 1.4,
        Math.min(1, bright[k] * 1.35 + 0.08),
        rng(),
      );
    }
    lines++;
  }

  // --- SCATTER + HUBS + MOTES ---------------------------------------------

  const sPos: number[] = [];
  const sSize: number[] = [];
  const sBright: number[] = [];
  const sRnd: number[] = [];

  const scatterTarget = N.scatterByTier[tier];
  let scatter = 0;
  guard = scatterTarget * 40;
  while (scatter < scatterTarget && guard-- > 0) {
    const x = range(B.minX + 20, B.maxX - 20);
    const z = range(B.minZ + 20, B.maxZ - 20);
    if (!visible(x, z, 1.4)) continue;
    const h = terrain.heightAt(x, z);
    probe.set(x, h, z);
    if (probe.distanceTo(camWorld) < 300) continue;

    const w =
      (0.25 + 0.75 * glowClusterAt(x, z)) *
      (0.22 +
        0.78 *
          Math.max(crestAt(x, z), channelAt(x, z) * 0.8, elevAt(h) * 0.6));
    if (rng() > Math.pow(w, 1.25)) continue;

    sPos.push(x, h + 0.4 + rng() * 1.4, z);
    sSize.push(1.2 + rng() * 2.0);
    const r = rng();
    sBright.push(w * (0.25 + 0.65 * r * r) * (1 + 0.5 * gatherAt(x, z)));
    sRnd.push(rng());
    scatter++;
  }

  // The on-line nodes join the same draw call.
  for (let i = 0; i < lineNodes.length; i += 6) {
    sPos.push(lineNodes[i], lineNodes[i + 1], lineNodes[i + 2]);
    sSize.push(lineNodes[i + 3]);
    sBright.push(lineNodes[i + 4]);
    sRnd.push(lineNodes[i + 5]);
  }

  /**
   * HUBS: scan the field on a coarse grid for genuine local summits. Energy
   * concentrates at peaks — the brief's strongest single instruction — and
   * only these nodes reach the ramp's top.
   */
  const hubCandidates: Array<{ x: number; z: number; h: number }> = [];
  const gs = N.hub.gridStep;
  for (let z = B.minZ + gs; z < B.maxZ - gs; z += gs) {
    for (let x = B.minX + gs; x < B.maxX - gs; x += gs) {
      const h = terrain.heightAt(x, z);
      if (h < N.hub.minHeight) continue;
      if (!visible(x, z, 1.3)) continue;
      const e = gs * 0.66;
      if (
        h > terrain.heightAt(x - e, z) &&
        h > terrain.heightAt(x + e, z) &&
        h > terrain.heightAt(x, z - e) &&
        h > terrain.heightAt(x, z + e) &&
        h > terrain.heightAt(x - e, z - e) &&
        h > terrain.heightAt(x + e, z + e)
      ) {
        hubCandidates.push({ x, z, h });
      }
    }
  }
  const hubStride = Math.max(1, Math.ceil(hubCandidates.length / N.hub.cap));
  for (let i = 0; i < hubCandidates.length; i += hubStride) {
    const { x, z, h } = hubCandidates[i];
    sPos.push(x + range(-6, 6), h + 1.2, z + range(-6, 6));
    sSize.push(range(N.hub.sizePx[0], N.hub.sizePx[1]));
    sBright.push(range(N.hub.bright[0], N.hub.bright[1]) + 0.25);
    sRnd.push(rng());
  }

  const mPos: number[] = [];
  const mSize: number[] = [];
  const mBright: number[] = [];
  const mRnd: number[] = [];

  const motesTarget = N.motesByTier[tier];
  let motes = 0;
  guard = motesTarget * 30;
  while (motes < motesTarget && guard-- > 0) {
    const x = range(B.minX + 20, B.maxX - 20);
    const z = range(B.minZ + 20, B.maxZ - 20);
    if (!visible(x, z, 1.45)) continue;
    const h = terrain.heightAt(x, z);
    probe.set(x, h, z);
    if (probe.distanceTo(camWorld) < 320) continue;

    const lift = rng();
    mPos.push(x, h + 2 + lift * lift * 12, z);
    mSize.push(0.8 + rng() * 0.8);
    mBright.push((0.06 + 0.16 * rng()) * (0.4 + 0.6 * glowClusterAt(x, z)));
    mRnd.push(rng());
    motes++;
  }

  // --- geometry + materials ------------------------------------------------

  const [c0, c1, c2, c3] = N.ramp;
  const rampUniforms = () => ({
    uC0: { value: new THREE.Color(c0) },
    uC1: { value: new THREE.Color(c1) },
    uC2: { value: new THREE.Color(c2) },
    uC3: { value: new THREE.Color(c3) },
  });

  const lineGeom = new THREE.BufferGeometry();
  lineGeom.setAttribute("position", new THREE.BufferAttribute(Float32Array.from(lPos), 3));
  lineGeom.setAttribute("aBright", new THREE.BufferAttribute(Float32Array.from(lBright), 1));
  lineGeom.setAttribute("aPath", new THREE.BufferAttribute(Float32Array.from(lPath), 1));
  lineGeom.setAttribute("aRnd", new THREE.BufferAttribute(Float32Array.from(lRnd), 1));

  const lineMat = new THREE.ShaderMaterial({
    vertexShader: lineVert(),
    fragmentShader: lineFrag(),
    uniforms: {
      uTime: { value: 0 },
      uMaster: { value: N.master },
      ...rampUniforms(),
    },
    blending: THREE.AdditiveBlending,
    transparent: true,
    depthWrite: false,
    depthTest: true,
  });

  const makePoints = (
    pos: number[],
    size: number[],
    brightArr: number[],
    rnd: number[],
    maxPx: number,
    drift: boolean,
  ) => {
    const g = new THREE.BufferGeometry();
    g.setAttribute("position", new THREE.BufferAttribute(Float32Array.from(pos), 3));
    g.setAttribute("aSize", new THREE.BufferAttribute(Float32Array.from(size), 1));
    g.setAttribute("aBright", new THREE.BufferAttribute(Float32Array.from(brightArr), 1));
    g.setAttribute("aRnd", new THREE.BufferAttribute(Float32Array.from(rnd), 1));
    const mat = new THREE.ShaderMaterial({
      vertexShader: pointVert(maxPx, drift),
      fragmentShader: POINT_FRAG,
      uniforms: {
        uTime: { value: 0 },
        uMaster: { value: N.master },
        uPointScale: { value: 1 },
        uCore: { value: new THREE.Color(PALETTE_CORE) },
        ...rampUniforms(),
      },
      blending: THREE.AdditiveBlending,
      transparent: true,
      depthWrite: false,
      depthTest: true,
    });
    const points = new THREE.Points(g, mat);
    points.frustumCulled = false;
    return points;
  };

  const linesObj = new THREE.LineSegments(lineGeom, lineMat);
  linesObj.frustumCulled = false;

  const scatterObj = makePoints(sPos, sSize, sBright, sRnd, 5.5, false);
  const motesObj = makePoints(mPos, mSize, mBright, mRnd, 2.2, true);

  const group = new THREE.Group();
  group.add(linesObj, scatterObj, motesObj);
  // After the terrain (renderOrder 1): the network needs the depth buffer the
  // land wrote, so a line running behind a ridge is genuinely hidden by it.
  group.renderOrder = 2;

  const materials = [lineMat, scatterObj.material, motesObj.material] as THREE.ShaderMaterial[];

  return {
    group,
    update(elapsed: number) {
      for (const m of materials) m.uniforms.uTime.value = elapsed;
    },
    setPointScale(scale: number) {
      (scatterObj.material as THREE.ShaderMaterial).uniforms.uPointScale.value = scale;
      (motesObj.material as THREE.ShaderMaterial).uniforms.uPointScale.value = scale;
    },
    dispose() {
      lineGeom.dispose();
      lineMat.dispose();
      scatterObj.geometry.dispose();
      (scatterObj.material as THREE.Material).dispose();
      motesObj.geometry.dispose();
      (motesObj.material as THREE.Material).dispose();
    },
  };
}

/** Hub cores only — the hottest yellow-green in the terrain's world, matching
 *  the particle ramp's own peak so the two systems share one identity. */
const PALETTE_CORE = "#d9ff9c";
